// <auto-generated />
using DataApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace DataApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180127224605_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DataApi.Models.OrderHeader", b =>
                {
                    b.Property<string>("clientID")
                        .HasMaxLength(50);

                    b.Property<string>("orderID")
                        .HasMaxLength(50);

                    b.Property<string>("busAddr1")
                        .HasMaxLength(50);

                    b.Property<string>("busAddr2")
                        .HasMaxLength(50);

                    b.Property<string>("busCity")
                        .HasMaxLength(50);

                    b.Property<string>("busCountry")
                        .HasMaxLength(50);

                    b.Property<string>("busName")
                        .HasMaxLength(50);

                    b.Property<string>("busState")
                        .HasMaxLength(50);

                    b.Property<string>("busZip")
                        .HasMaxLength(50);

                    b.Property<string>("contTel")
                        .HasMaxLength(50);

                    b.Property<string>("dcNum")
                        .HasMaxLength(50);

                    b.Property<string>("deptNum")
                        .HasMaxLength(50);

                    b.Property<string>("ordNum")
                        .HasMaxLength(50);

                    b.Property<string>("orderType")
                        .HasMaxLength(50);

                    b.Property<string>("paymentType")
                        .HasMaxLength(50);

                    b.Property<string>("poNum")
                        .HasMaxLength(50);

                    b.Property<string>("reqDeliveryDate")
                        .HasMaxLength(50);

                    b.Property<string>("reqShipDate")
                        .HasMaxLength(50);

                    b.Property<string>("rsaFlag")
                        .HasMaxLength(50);

                    b.Property<string>("rushFlag")
                        .HasMaxLength(50);

                    b.Property<string>("salesOrdNum")
                        .HasMaxLength(50);

                    b.Property<string>("serviceLevel")
                        .HasMaxLength(50);

                    b.Property<string>("shipAddr1")
                        .HasMaxLength(50);

                    b.Property<string>("shipAddr2")
                        .HasMaxLength(50);

                    b.Property<string>("shipCity")
                        .HasMaxLength(50);

                    b.Property<string>("shipCountry")
                        .HasMaxLength(50);

                    b.Property<string>("shipName")
                        .HasMaxLength(50);

                    b.Property<string>("shipState")
                        .HasMaxLength(50);

                    b.Property<string>("shipToCustNum")
                        .HasMaxLength(50);

                    b.Property<string>("shipZip")
                        .HasMaxLength(50);

                    b.Property<string>("soldToCustNum")
                        .HasMaxLength(50);

                    b.Property<string>("storeName")
                        .HasMaxLength(50);

                    b.Property<string>("storeNum")
                        .HasMaxLength(50);

                    b.Property<string>("totalPrice")
                        .HasMaxLength(50);

                    b.HasKey("clientID", "orderID");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("DataApi.Models.ShipConfirm", b =>
                {
                    b.Property<string>("clientID")
                        .HasMaxLength(50);

                    b.Property<string>("orderID")
                        .HasMaxLength(50);

                    b.Property<bool>("hasSent");

                    b.Property<string>("trackNum")
                        .HasMaxLength(50);

                    b.HasKey("clientID", "orderID");

                    b.ToTable("ShipConfirms");
                });
#pragma warning restore 612, 618
        }
    }
}
