// <auto-generated />
using DataApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace DataApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180127171842_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DataApi.Models.ShipConfirm", b =>
                {
                    b.Property<string>("ClientID")
                        .HasMaxLength(50);

                    b.Property<string>("OrderID")
                        .HasMaxLength(50);

                    b.Property<bool>("HasSent");

                    b.Property<string>("TrackNum")
                        .HasMaxLength(50);

                    b.HasKey("ClientID", "OrderID");

                    b.ToTable("ShipConfirms");
                });
#pragma warning restore 612, 618
        }
    }
}
