// <auto-generated />
using DataApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DataApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180117203805_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataApi.Models.ShipConfirm", b =>
                {
                    b.Property<string>("ClientID");

                    b.Property<string>("OrderID");

                    b.Property<bool>("HasSent");

                    b.Property<string>("TrackNum");

                    b.HasKey("ClientID", "OrderID");

                    b.ToTable("ShipConfirms");
                });
#pragma warning restore 612, 618
        }
    }
}
